#include "code\objectives\final_objective\battle_royale.dm"
#include "code\objectives\final_objective\battlecruiser.dm"
#include "code\objectives\final_objective\final_objective.dm"
#include "code\objectives\final_objective\infect_ai.dm"
#include "code\objectives\final_objective\no_escape.dm"
#include "code\objectives\final_objective\objective_dark_matteor.dm"
#include "code\objectives\final_objective\romerol.dm"
#include "code\objectives\final_objective\supermatter_cascade.dm"

#include "code\objectives\abstract\target_player.dm"
#include "code\objectives\assassination.dm"
#include "code\objectives\demoralise_assault.dm"
#include "code\objectives\destroy_heirloom.dm"
#include "code\objectives\destroy_item.dm"
#include "code\objectives\eyesnatching.dm"
#include "code\objectives\hack_comm_console.dm"
#include "code\objectives\infect.dm"
#include "code\objectives\kidnapping.dm"
#include "code\objectives\kill_pet.dm"
#include "code\objectives\locate_weakpoint.dm"
#include "code\objectives\sabotage_machinery.dm"
#include "code\objectives\steal.dm"


/datum/modpack/progressive_traitor
	id = ""
	name = ""
	group = "Features"
	desc = ""
	author = ""

