#include "code\loadout_items.dm"
#include "code\client\loadout_override_preference.dm"
#include "code\items\role_restricted\accessories.dm"
#include "code\items\role_restricted\glasses.dm"
#include "code\items\role_restricted\head.dm"
#include "code\items\role_restricted\inhands.dm"
#include "code\items\role_restricted\neck.dm"
#include "code\items\role_restricted\pocket.dm"
#include "code\items\role_restricted\shoes.dm"
#include "code\items\role_restricted\suits.dm"
#include "code\items\role_restricted\under.dm"
#include "code\ui\loadout_outfit.dm"

/datum/modpack/metaloadouts
	id = "metacoins"
	name = "Лодауты"
	group = "Features"
	desc = "Вещи в лодауте для ролей."
	author = "Glamyr"
