#include "code\loadout_items.dm"
#include "code\client\loadout_override_preference.dm"
#include "code\items\accessories.dm"
#include "code\items\glasses.dm"
#include "code\items\head.dm"
#include "code\items\inhands.dm"
#include "code\items\neck.dm"
#include "code\items\pocket.dm"
#include "code\items\shoes.dm"
#include "code\items\suits.dm"
#include "code\items\under.dm"
#include "code\ui\loadout_outfit.dm"

/datum/modpack/metaloadouts
	id = "metacoins"
	name = "Лодауты"
	group = "Features"
	desc = "Вещи в лодауте для ролей."
	author = "Glamyr"
